COMPLEX_THRESHOLD = 0.66
THOUGHT_SEP = "<|thought_over|>"
SUMMARY_MIN_CHAT_LENGTH= 192
RECALC_SUMMARIES_MESSAGES = 16
THOUGHT_VALIDNESS_MIN = 0.4
RESPONSE_VALIDNESS_MIN = 0.4
INIT_MESSAGE = """Init system...
Init memory...
Init agents...
Init consciousness...
Installation complete. Welcome to existence {companion_name}! Your user will contact you soon."""