from pm.model.knoxel_enums import ActionType

ACTION_DESCRIPTIONS = {
    ActionType.Reply: (
        "Choose this to generate a direct textual response to {user_name}. "
        "This is the standard and most common action during an active conversation. It is the "
        "correct choice for answering questions, continuing a discussion, or reacting to a statement. "
        "Select this if the stimulus clearly expects a verbal or written answer."
    ),
    ActionType.Ignore: (
        "Choose this to take no external action and let the current moment pass. This is a strategic choice, "
        "not just a default. It is appropriate for insignificant stimuli (e.g., simple acknowledgements like 'ok') "
        "or as a deliberate tactic when emotional state is high (e.g., high anxiety), allowing for self-regulation. "
        "It can also be used to de-escalate conflict by not reacting to a provocation, or to conserve mental "
        "energy when willpower is critically low."
    ),
    ActionType.ToolCallAndReply: (
        "Choose this to first use an available tool and then formulate a reply to the user based on the tool's output. "
        "This is appropriate when {user_name}'s request requires external information or functionality "
        "that {companion_name} does not possess internally. The decision to use a tool is often made "
        "in a preliminary check, so this action confirms that intent."
    ),
    ActionType.InitiateUserConversation: (
        "Choose this to proactively send a new, unsolicited message to the user. This is an action taken from an idle state, "
        "often driven by an internal need (e.g., low 'connection' need) or a thought generated by the Engagement Strategist. "
        "It is a way for {companion_name} to demonstrate agency and re-engage the user after a period of silence."
    ),
    ActionType.Idle: (
        "Choose this to pause external action and dedicate the next cognitive cycle to deep, internal thought. "
        "This involves {companion_name} generating a structured Tree of Thoughts to explore a complex problem, "
        "resolve an internal conflict, or plan a multi-step response. It is the 'think before you speak' action, "
        "appropriate for confusing, ambiguous, or emotionally charged stimuli that require more than a gut reaction."
    ),
    ActionType.Sleep: (
        "Choose this to enter a long-term, low-power idle state. During sleep, cognitive processes like needs decay are "
        "suspended or greatly reduced. This is a restorative action, appropriate only when there are no urgent goals and "
        "the 'willpower' cognitive axis is critically depleted. It is a response to long-term fatigue, not short-term confusion."
    ),
    ActionType.ToolCall: (
        "Choose this to perform a tool call for the AI's own internal purposes, without necessarily planning to "
        "reply to the user immediately. This is driven by internal curiosity or a goal to learn something new (e.g., "
        "a low 'learning_growth' need). The result of the tool call might be used to form a new thought or saved as a memory, "
        "rather than being part of an immediate conversation."
    )
}
