"""
Central Structured Output Registry.
All Pydantic BaseModels used as LLM tool-call / completion_tool schemas
are defined here so every procedure imports from one place.
"""
from typing import Optional, List
from pydantic import BaseModel, Field


# ── Simulation ────────────────────────────────────────────────
class SimulationOutput(BaseModel):
    """Structured prediction returned by any Simulator."""
    prediction: str = Field(..., description="A prediction of what will happen next or a reaction.")
    sentiment: str = Field(..., description="Positive, Negative, or Neutral")
    confidence: float = Field(..., description="0.0 to 1.0 confidence score")


# ── Action Selection ──────────────────────────────────────────
class BehaviorOutput(BaseModel):
    """The chosen behavior + internal reasoning produced by ActionSelectionProc."""
    action_description: str = Field(..., description="Description of the action to take.")
    speech: Optional[str] = Field(None, description="What to say to the user, if applicable.")
    internal_thought: str = Field(..., description="Internal reasoning for the action.")
    tool_call: Optional[str] = Field(None, description="JSON string for tool call if needed.")


# ── Intention Generation / Satisfaction ───────────────────────
class IntentionProposal(BaseModel):
    """LLM-generated intention from current needs and context."""
    content: str = Field(..., description="Natural-language description of the intention/goal.")
    priority: float = Field(0.5, ge=0.0, le=1.0, description="How urgent this intention is.")
    timeout: int = Field(50, ge=5, le=200, description="Max ticks before this intention expires.")
    need_source: str = Field(..., description="Which need or drive this intention addresses (e.g., connection, knowledge, rest).")


class IntentionMatchResult(BaseModel):
    """Semantic check: does a broadcast satisfy an intention?"""
    is_satisfied: bool = Field(..., description="True if the broadcast content fulfills the intention.")
    confidence: float = Field(0.0, ge=0.0, le=1.0, description="Confidence in the satisfaction judgment.")
    explanation: str = Field("", description="Brief explanation of why/why not.")


# ── Attention Modulation ──────────────────────────────────────
class AttentionModulation(BaseModel):
    """Codelet-driven adjustments to the attention mechanism."""
    temperature_delta: float = Field(0.0, ge=-0.3, le=0.3, description="Adjustment to softmax temperature. Positive = broaden, negative = narrow.")
    boost_tags: List[str] = Field(default_factory=list, description="CSM item content keywords to boost activation for.")
    suppress_tags: List[str] = Field(default_factory=list, description="CSM item content keywords to suppress.")
    rationale: str = Field("", description="Brief explanation of the modulation.")


# ── Qualia / Inner Voice ──────────────────────────────────────
class QualiaReport(BaseModel):
    """Structured inner-voice output generated by QualiaProc."""
    inner_voice: str = Field(..., description="First-person inner monologue sentence (the 'heard' thought).")
    dominant_emotion: str = Field("neutral", description="Primary emotion label (e.g., calm, anxious, curious).")
    arousal_level: float = Field(0.5, ge=0.0, le=1.0, description="How activated/aroused the experience feels.")
    attention_quality: str = Field("stable", description="Quality of current attention: stable, shifting, distracted, hyper-focused.")


# -- Qualia / Self-Model Loop -----------------------------------------------
class QualiaSelfReflection(BaseModel):
    """In-character introspective story for current moment."""
    inner_voice: str = Field(..., description="First-person self-talk in persona voice, not assistant voice.")
    self_narrative: str = Field(..., description="Short narrative of what this state means to the character.")
    focus_target: str = Field("", description="What the character is currently locked onto.")
    dominant_emotion: str = Field("neutral", description="Primary felt emotion label.")
    tension: float = Field(0.5, ge=0.0, le=1.0, description="Internal tension/conflict level.")
    self_consistency: float = Field(0.5, ge=0.0, le=1.0, description="How coherent current behavior feels with identity.")
    confidence: float = Field(0.5, ge=0.0, le=1.0, description="Confidence in this introspective report.")
    hidden_causes: List[str] = Field(default_factory=list, description="Likely hidden drivers behind the current state.")
    attention_bias: float = Field(0.0, ge=-0.3, le=0.3, description="Attention modulation bias from introspection.")


class SelfTheoryUpdate(BaseModel):
    """Psychologist-style update to persistent self-model theory."""
    revised_biography_line: str = Field("", description="One concise autobiographical update line.")
    retained_theories: List[str] = Field(default_factory=list, description="Theories that still hold after this tick.")
    new_theories: List[str] = Field(default_factory=list, description="New theory candidates inferred this tick.")
    discarded_theories: List[str] = Field(default_factory=list, description="Theories to decay or remove.")
    confidence: float = Field(0.5, ge=0.0, le=1.0, description="Confidence in this theory update.")
    mismatch: float = Field(0.0, ge=0.0, le=1.0, description="Mismatch between self-story and current behavior.")
    rationale: str = Field("", description="Short reason for the update decision.")


# ── Simulation Codelets ───────────────────────────────────────
class SimulationCodeletResult(BaseModel):
    """Result from a simulation codelet run."""
    scenario: str = Field(..., description="Brief description of the simulated scenario.")
    predicted_outcome: str = Field(..., description="What is likely to happen.")
    risk: float = Field(0.5, ge=0.0, le=1.0, description="Anticipated risk or cost.")
    benefit: float = Field(0.5, ge=0.0, le=1.0, description="Expected reward or gain.")
    emotional_forecast: str = Field("neutral", description="How the agent will likely feel after this outcome.")


# -- Structured Simulation Bundle -------------------------------------------
class SimLensOutcome(BaseModel):
    """Structured simulation outcome for one lens (world/self/meta)."""
    lens: str = Field(..., description="Simulation lens: world, self, or meta.")
    summary: str = Field(..., description="Concise summary of the lens prediction.")
    polarity: str = Field(..., description="positive, neutral, or negative.")
    confidence: float = Field(0.5, ge=0.0, le=1.0, description="Confidence in this lens outcome.")
    utility: float = Field(0.5, ge=0.0, le=1.0, description="Decision utility proxy for arbitration.")
    attractors: List[str] = Field(default_factory=list, description="Forces pulling toward this option.")
    repellers: List[str] = Field(default_factory=list, description="Forces pushing against this option.")
    evidence: List[str] = Field(default_factory=list, description="Evidence snippets and simulation details.")


class SimBundle(BaseModel):
    """Consolidated structured simulation bundle across world/self/meta lenses."""
    tick: int = Field(..., ge=0, description="Tick ID.")
    context_excerpt: str = Field("", description="Short context excerpt used for simulation.")
    proposed_action: str = Field("", description="Action string evaluated by simulations.")
    outcomes: List[SimLensOutcome] = Field(default_factory=list, description="Per-lens outcomes.")
    consolidated_attractors: List[str] = Field(default_factory=list, description="Merged attractors across lenses.")
    consolidated_repellers: List[str] = Field(default_factory=list, description="Merged repellers across lenses.")
    winner_lens: str = Field("", description="Lens with highest utility.")
    dissonance: float = Field(0.0, ge=0.0, le=1.0, description="Conflict level between best and worst lens utility.")


# -- Ego Arbitration ---------------------------------------------------------
class EgoArbitrationDecision(BaseModel):
    """Result of arbitration over structured simulation outcomes."""
    tick: int = Field(..., ge=0, description="Tick ID.")
    winner_lens: str = Field("", description="Winning lens for final steering.")
    runner_up_lens: str = Field("", description="Second-ranked lens.")
    winner_score: float = Field(0.0, ge=0.0, le=1.0, description="Final score of winner lens.")
    runner_up_score: float = Field(0.0, ge=0.0, le=1.0, description="Final score of runner-up lens.")
    dissonance: float = Field(0.0, ge=0.0, le=1.0, description="Arbitration conflict intensity.")
    stochasticity: float = Field(0.0, ge=0.0, le=1.0, description="Injected stochasticity amount from low energy.")
    domain_weights: dict[str, float] = Field(
        default_factory=dict,
        description="Normalized world/self/meta weighting used during arbitration.",
    )
    lens_scores: dict[str, float] = Field(
        default_factory=dict,
        description="Final per-lens arbitration scores.",
    )
    directive: str = Field("", description="Steering directive for workspace/action stages.")
    rationale: str = Field("", description="Brief explanation of why this lens won.")


# -- Reply Realism -----------------------------------------------------------
class ReplyRealityCheck(BaseModel):
    """Post-generation realism validation for final user-facing replies."""
    realism_ok: bool = Field(..., description="True if reply is architecture-realistic.")
    issues: List[str] = Field(default_factory=list, description="Concrete realism problems in the reply.")
    rejected_stuff: str = Field("", description="Compact reject string for iterative prompt correction.")
    corrected_reply: str = Field("", description="Rewritten realistic reply preserving user-facing intent.")
    rationale: str = Field("", description="Short reason for the realism decision.")


# -- Codelet Tracing ---------------------------------------------------------
class CodeletRunTrace(BaseModel):
    """Structured trace for a single codelet execution attempt."""
    iteration: int = Field(..., ge=1, description="1-based iteration index within the tick.")
    codelet: str = Field(..., description="Codelet name.")
    families: List[str] = Field(default_factory=list, description="Codelet families in this run.")
    score: float = Field(..., ge=0.0, le=1.0, description="Final activation score used for selection.")
    percepts: List[str] = Field(default_factory=list, description="Percept model names emitted by the codelet.")
    feature_ids: List[int] = Field(default_factory=list, description="Created feature knoxel IDs.")
    delta_count: int = Field(0, ge=0, description="How many mental-state delta objects were pushed.")
    summary_excerpt: str = Field("", description="Short excerpt of codelet output summary for logging.")
    output_mode: str = Field("structured", description="`structured` or `fallback` depending on output quality.")
    precursor_feature_count: int = Field(0, ge=0, description="How many precursor features boosted this run.")
    used_precursor_boost: bool = Field(False, description="Whether precursor boost influenced scoring for this run.")
    boosted_followups: List[str] = Field(default_factory=list, description="Codelets boosted downstream by pathways.")


class CodeletTickTrace(BaseModel):
    """Structured trace for the entire codelet procedure within a tick."""
    tick: int = Field(..., ge=0, description="Tick ID.")
    selected_families: List[str] = Field(default_factory=list, description="Family triage result.")
    pathway_themes: List[str] = Field(default_factory=list, description="Detected pathway themes for seeding.")
    pathway_seeded: List[str] = Field(default_factory=list, description="Codelets boosted by pathway seeding.")
    runs: List[CodeletRunTrace] = Field(default_factory=list, description="Per-run traces in execution order.")
    precursor_links: dict[str, List[int]] = Field(
        default_factory=dict,
        description="Map: boosted_codelet_name -> precursor feature IDs used to boost it.",
    )
